const HTTP_RESPONSES = {
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    INTERNAL_SERVER_ERROR: 500,
    NOT_FOUND: 404,
    BAD_REQUEST_CONTENT: 'Bad request',
  }
  module.exports = HTTP_RESPONSES